---

- name: Install packages
  dnf: name={{ item }} state=present
  with_items:
    - xmonad
    - xmobar
    - dmenu
    - rxvt-unicode
    - xloadimage
    - xbacklight
    - xscreensaver
    - pmount
    - pavucontrol
    - alsa-utils
    - redshift
    - NetworkManager-tui

- name: Make sure patch is installed
  dnf: name=patch state=present

- name: Make Xsession souce ~/.xprofile script (BZ 845339 workaround)
  patch:
     src=roles/custom-xmonad-desktop/files/bz845339-hack.patch
     dest=/etc/X11/xinit/Xsession

# TODO: make it more general, maybe use xuserrun or some systemd hack?
# https://wiki.archlinux.org/index.php/XScreenSaver
- name: Service xscreensaver-lock (lock screen before sleep or suspend)
  template:
    src=xscreensaver-lock.service
    dest=/etc/systemd/system/xscreensaver-lock.service

- name: Enable xscreensaver-lock
  service: name=xscreensaver-lock enabled=yes
