---

- name: Install packages
  dnf:
    name:
      - xmonad
      - xmobar
      - dmenu
      - rxvt-unicode
      - rxvt-unicode-256color-ml
      - xloadimage
      - xbacklight
      - xscreensaver
      - pmount
      - pavucontrol
      - alsa-utils
      - redshift
      - NetworkManager-tui
    state: present

# TODO: make it more general, maybe use xuserrun or some systemd hack?
# https://wiki.archlinux.org/index.php/XScreenSaver
- name: Service xscreensaver-lock (lock screen before sleep or suspend)
  template:
    src=xscreensaver-lock.service
    dest=/etc/systemd/system/xscreensaver-lock.service

- name: Enable xscreensaver-lock
  service: name=xscreensaver-lock enabled=yes
