---

#
# https://docs.fedoraproject.org/en-US/Fedora/22/html/Installation_Guide/sect-common-post-installation-tasks.html
#

- name: Check that we run on Fedora
  assert:
    that:
      - '"{{ ansible_distribution }}" == "Fedora"'

- name: Update system
  dnf: name='*' state=latest
  when: update_forced == true

#
# http://rpmfusion.org/keys
#

- name: Install distribution-gpg-keys package
  dnf:
    name: distribution-gpg-keys
    state: present

- name: Import rpm-gpg key of rpmfusion free repo
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/rpmfusion//RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}'

- name: Import rpm-gpg key of rpmfusion nonfree repo
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/rpmfusion//RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}
  when: addrepo_rpmfusion_nonfree == true

- name: Import rpm-gpg key of adobe linux repo
  rpm_key:
    state: present
    key: '/usr/share/distribution-gpg-keys/adobe/RPM-GPG-KEY-adobe-linux'
  when: addrepo_adobe == true

#
# http://rpmfusion.org/Configuration
#

- name: Install rpmfusion free repo
  dnf:
    name=https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state=present

- name: Install rpmfusion nonfree repo
  dnf:
    name=https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state=present
  when: addrepo_rpmfusion_nonfree == true

- name: Install adobe linux repo
  dnf:
    name=http://linuxdownload.adobe.com/adobe-release/adobe-release-{{ ansible_userspace_architecture }}-1.0-1.noarch.rpm
    state=present
  when: addrepo_adobe == true
