---
- name: Fedora workstation post-installation system setup
  hosts: localhost
  connection: local

  vars:
    do_not_access_home_dir: false
    firewall_type: firewalld

  roles:
   - fedora-ansible-dependencies
   - etckeeper
   - fedora-common
   - firewall
   - role: sshd
     ssh_allow_users:
      - root
      - martin
   - user-root
   - role: users
     main_user_name: martin
     main_user_comment: 'Martin B.'
   - user-makerpm
   - lightdm
   - role: custom-xmonad-desktop
     xscreensaver_lock_username: martin
   - role: mpd
     mpd_username: martin
   - role: virtualization
     libvirt_users:
      - martin
   - local-dns
   - packages-martin
   - role: cups-printer-xerox
     when: cups_printer_xerox_ppd_file is defined
