---
- name: Fedora post-installation setup for saturn machine
  hosts: localhost
  connection: local

  vars:
    do_not_access_home_dir: false
    firewall_type: firewalld

  roles:
   - fedora-ansible-dependencies
   - fedora-common
   - firewall
   - user-root
   - role: users
     main_user_name: jarek
     additional_users:
      - martin
      - tomas
      - hana
      - backup
   - role: sddm
     sddm_hide_users:
      - backup
   - role: virtualization
     libvirt_users:
      - jarek
      - hana
   - role: cups-printer-xerox
     cups_printer_xerox_ppd_file: /root/data/xerox/cd/Linux/xerox.ppd/ph3250.ppd
   - packages-bk
