---
- name: Fedora post-installation setup for telesto
  hosts: localhost
  connection: local

  vars:
    do_not_access_home_dir: false
    firewall_type: firewalld

  roles:
   - fedora-ansible-dependencies
   - etckeeper
   - role: fedora-common
     update_forced: false
   - firewall
   - sshd
   - user-root
   - role: users
     additional_users: []
   - user-makerpm
   - lightdm
   - role: custom-xmonad-desktop
     xscreensaver_lock_username: martin
   - role: mpd
     mpd_username: martin
   - workstation
