---

#
# Local DNS server
#

- name: Enable local DNS server (networkmanager dnsmasq)
  ini_file: dest=/etc/NetworkManager/NetworkManager.conf
            section=main
            option=dns
            value=dnsmasq
            state=present
  notify:
   - restart networkmanager
