---

# Originally based on
# https://fedoramagazine.org/getting-ansible-working-fedora-23/
# (for local usage only).
# But since Fedora 28, it just installs python3 subpackages.

- name: Install python3-firewall for firewalld module
  dnf: name=python3-firewall state=present

- name: Install python3-libselinux
  dnf: name=python3-libselinux state=present
