---

# Originally based on
# https://fedoramagazine.org/getting-ansible-working-fedora-23/, but for local
# usage only. Since Fedora 28, it just installs python3 subpackages instead of
# python2 ones as ansible version packaged in Fedora 28 already allows one to
# switch to python 3 for ansible managed node processess (this fixes problem
# with missing python2-firewall package).

- name: Install python3-firewall for firewalld module
  dnf: name=python3-firewall state=present

- name: Install python3-libselinux
  dnf: name=python3-libselinux state=present
