---

# based on https://fedoramagazine.org/getting-ansible-working-fedora-23/
# but for local usage only

- name: Check if python2-dnf is installed
  command: rpm -q python2-dnf
  register: rpm_q_python2_dnf
  changed_when: False
  failed_when: rpm_q_python2_dnf.rc > 1

- name: Install python2-dnf for dnf module
  command: dnf install -y python2-dnf
  when: rpm_q_python2_dnf.rc == 1

- name: Install python2-firewall for firewalld module
  dnf: name=python2-firewall state=present

- name: Install python2-libselinux
  dnf: name=python2-libselinux state=present
