---

- name: Install additional packages
  dnf:
    name:
     - vim
     - mc
     - vifm
     - tmux
     - htop
     - vlc
     - mplayer
     - pandoc
     - pmount
     - firefox
     - thunderbird
     - thunderbird-enigmail
     - keepassx
     - audacity
     - gimp
     - geeqie
     - nmap
     - ddrescue
     - fbreader
     - libreoffice
     - libreoffice-help-cs
     - libreoffice-langpack-cs
     - unoconv
    state: present
  tags: install-packages
