---

- name: Install additional packages
  dnf: name={{ item }} state=present
  tags: install-packages
  with_items:
   - vim
   - mc
   - vifm
   - tmux
   - htop
   - vlc
   - mplayer
   - pandoc
   - pmount
   - firefox
   - thunderbird
   - thunderbird-enigmail
   - keepassx
   - audacity
   - gimp
   - geeqie
   - nmap
   - ddrescue
   - fbreader
   - libreoffice
   - libreoffice-help-cs
   - libreoffice-langpack-cs
   - unoconv
