---

#
# Create user accounts
#

- assert:
    that:
      - main_user_name is defined
    msg: >
      You need to specify unix username of main user account in
      main_user_name variable!

- name: Create main user group
  group: name={{ main_user_name }} gid=1000 state=present

- name: Create main user account
  user: name={{ main_user_name }}
        group={{ main_user_name }}
        groups=users
        uid=1000
        home=/home/{{ main_user_name }}
        createhome={{ do_not_access_home_dir == false }}
        shell=/bin/bash
        state=present

- name: Set comment for main user account
  user: name={{ main_user_name }}
        comment={{ main_user_comment }}
  when: main_user_comment is defined

- name: Groups for additional user accounts
  group: name={{ item }} state=present
  with_items: "{{ additional_users }}"

- name: Additional user accounts
  user: name={{ item }}
        group={{ item }}
        createhome={{ do_not_access_home_dir == false }}
        shell=/bin/bash
        state=present
  with_items: "{{ additional_users }}"

#
# Shared directory
#

- name: Create shared dir in /home
  file: path=/home/shared state=directory
        owner=root group=users mode=2755
  when: do_not_access_home_dir == false

- name: Create dirs in /home/shared
  file: path=/home/shared/{{ item }} state=directory
        owner=root group=users mode=3775
  when: do_not_access_home_dir == false
  with_items:
   - documentaries
   - images
   - lectures
   - movies
   - music
   - podcast
   - series
