---

- name: Install additional packages
  dnf:
    name:
     - vim
     - gvim
     - tmux
     - vifm
     - mc
     - htop
     - lshw
     - acpi
     - wget
     - curl
     - wipe
     - ipython
     - python3-ipython
     - pylint
     - python3-pylint
     - python3-q
     - python-ctags
     - xmlstarlet
     - jq
     - git
     - git-annex
     - tig
     - gitk
     - meld
     - terminator
     - pandoc
     - gitit
     - pmount
     - firefox
     - thunderbird
     - thunderbird-enigmail
     - keepassx
     - ruby
     - ruby-irb
     - mutt
     - notmuch-mutt
     - abook
     - goobook
     - msmtp
     - offlineimap
     - graphviz
     - epydoc
     - mercurial
     - darcs
     - fedpkg
     - audacity
     - unoconv
     - qstardict
     - libappindicator
     - libappindicator-gtk3
     - pavucontrol
     - geeqie
     - nmap
     - tigervnc
     - ddrescue
     - fbreader
     - terminus-fonts
     - terminus-fonts-console
     - git-cal
     - iotop
     - mplayer
     - ffmpeg
    state: present
  tags: install-packages
