---

- name: Make sure lightdm-kde is not installed
  dnf: name=lightdm-kde state=absent

- name: Install lightdm packages
  dnf: name={{ item }} state=installed
  with_items:
   - lightdm
   - lightdm-gtk
   - light-locker

- name: Disable guest login
  lineinfile: dest=/etc/lightdm/lightdm.conf
              regexp='^#? ?allow-guest ?='
              line='allow-guest = false'
              state=present

- name: Show manual login box
  lineinfile: dest=/etc/lightdm/lightdm.conf
              regexp='{{ item.exp }}'
              line='{{ item.val }}'
              state=present
  with_items:
   - exp: '^#? ?greeter-hide-users ?='
     val: 'greeter-hide-users = true'
   - exp: '^#? ?greeter-show-manual-login ?='
     val: 'greeter-show-manual-login = true'

- name: BZ 1581495 workaround (drop kwallet pam module from lightdm)
  lineinfile:
    dest=/etc/pam.d/lightdm
    regexp='pam_kwallet.?.so'
    state=absent

- name: Check if sddm is installed
  command: rpm -q sddm
  register: rpm_q_sddm
  changed_when: False
  failed_when: rpm_q_sddm.rc > 1
  args:
    warn: False

- name: Disable sddm (Fedora 22 default for KDE/Plasma)
  service: name=sddm enabled=no
  when: rpm_q_sddm.rc == 0

- name: Stop sddm
  service: name=sddm state=stopped
  when: rpm_q_sddm.rc == 0

- name: Enable lightdm
  service: name=lightdm enabled=yes

# may fail, TODO: commenting this out if it actually still fails
- name: Start lightdm
  service: name=lightdm state=started
