---

- name: Install gitit packages
  dnf:
    name:
     - gitit
     - texlive-ulem
    state: present
  when: ansible_user == "root"

- assert:
    that:
      - gitit_username is defined

- debug:
    msg: "Setting up personal wiki for {{ gitit_username }} user account."

# TODO: test and tweak this task
- name: Restrict local access to gitit port (iptables)
  lineinfile:
    dest: '/etc/sysconfig/{{ item }}'
    line: '-A OUTPUT {{ gitit_iptables_rule }}'
    insertbefore: '^COMMIT'
    state: present
  with_items:
   - iptables
  notify:
   - restart iptables
  when: firewall_type == "iptables"

- name: Get direct rules (firewalld)
  command: 'firewall-cmd --direct --get-rules ipv4 filter OUTPUT'
  changed_when: false
  register: firewalld_get_rules
  when: firewall_type == "firewalld"

- name: Get list of direct rules from get-rules output (firewalld)
  set_fact:
    firewalld_rules: "{{ firewalld_get_rules.stdout|regex_replace('.!.', '!') }}"
  when: firewall_type == "firewalld"

- name: Restrict local access to gitit port (firewalld)
  command: "{{ item }}"
  with_items:
   - 'firewall-cmd --direct --add-rule ipv4 filter OUTPUT 0 {{ gitit_iptables_rule }}'
   - 'firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 {{ gitit_iptables_rule }}'
  when: firewall_type == "firewalld" and not (gitit_iptables_rule in firewalld_rules)

- name: User setup of gitit personal wiki
  block:

    - name: Create gitit directory
      file:
        path: "{{ gitit_work_dir }}"
        state: directory

    - name: Initialize gitit.conf file
      shell: gitit --print-default-config > gitit.conf
      args:
        chdir:   "{{ gitit_work_dir }}"
        creates: "{{ gitit_work_dir }}/gitit.conf"

    - name: Configure gitit
      lineinfile:
        path: "{{ gitit_work_dir }}/gitit.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: '^#?address:'
          line: 'address: 127.0.0.1'
        - regexp: '^#?port:'
          line: 'port: {{ gitit_port }}'
        - regexp: '^#?wiki-title:'
          line: 'wiki-title: Personal Wiki'
        - regexp: '^#?repository-path:'
          line: 'repository-path: {{ gitit_repo_dir }}'
        - regexp: '^#?math:'
          line: 'math: MathML'
        - regexp: '^#?pdf-export:'
          line: 'pdf-export: yes'
      notify:
        - restart gitit

    - name: Create gitit service file
      template:
        src: roles/gitit-personal-wiki/files/gitit.service.j2
        dest: ~/.config/systemd/user/gitit.service

    - name: Enable gitit service
      service:
        name: gitit
        enabled: yes
        user: yes
      when: ansible_user != "root"

  become: True
  become_user: "{{ gitit_username }}"
