---

- assert:
    that:
      - ssh_allow_users is defined
      - "{{ ssh_allow_users | length }} > 0"
    msg:
      - "list ssh_allow_users should contain at least one username"

#
# sshd setup
#

- name: Make sure ssh server is installed
  dnf: name=openssh-server state=installed

- name: Enable sshd
  service: name=sshd enabled=yes

- name: Configure ssh daemon
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='{{ item.exp }}'
              line='{{ item.val }}'
              state=present
  with_items:
   - exp: '^PasswordAuthentication'
     val: 'PasswordAuthentication no'
   - exp: '^#?HostbasedAuthentication'
     val: 'HostbasedAuthentication no'
   - exp: '^#?IgnoreRhosts'
     val: 'IgnoreRhosts yes'
   - exp: '^#?Protocol'
     val: 'Protocol 2'
  notify:
    - restart sshd

- name: Set AllowUsers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ssh_allow_users | join(' ') }}"
    state: present
  notify:
    - restart sshd

- name: First start of sshd to generate keys
  command: systemctl start sshd
  args:
    creates: /etc/ssh/ssh_host_rsa_key

#
# firewall setup
#

- name: Open ssh port in iptables
  lineinfile:
    dest=/etc/sysconfig/{{ item }}
    line='-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
    insertbefore='^COMMIT'
    state=present
  with_items:
   - iptables
   - ip6tables
  notify:
    - restart iptables
  when: firewall_type == "iptables"

- name: Open ssh port in firewalld
  firewalld: service=ssh permanent=true immediate=true state=enabled
  when: firewall_type == "firewalld"
